<?php

//Catálogo N° 02:

return [
    'AFN' => ['id' => 'AFN', 'value' => 'Afghani'],
    'EUR' => ['id' => 'EUR', 'value' => 'Euro'],
    'ALL' => ['id' => 'ALL', 'value' => 'Lek'],
    'DZD' => ['id' => 'DZD', 'value' => 'Algerian Dinar'],
    'USD' => ['id' => 'USD', 'value' => 'US Dollar'],
    'AOA' => ['id' => 'AOA', 'value' => 'Kwanza'],
    'XCD' => ['id' => 'XCD', 'value' => 'East Caribbean Dollar'],
    'ARS' => ['id' => 'ARS', 'value' => 'Argentine Peso'],
    'AMD' => ['id' => 'AMD', 'value' => 'Armenian Dram'],
    'AWG' => ['id' => 'AWG', 'value' => 'Aruban Florin'],
    'AUD' => ['id' => 'AUD', 'value' => 'Australian Dollar'],
    'AZN' => ['id' => 'AZN', 'value' => 'Azerbaijan Manat'],
    'BSD' => ['id' => 'BSD', 'value' => 'Bahamian Dollar'],
    'BHD' => ['id' => 'BHD', 'value' => 'Bahraini Dinar'],
    'BDT' => ['id' => 'BDT', 'value' => 'Taka'],
    'BBD' => ['id' => 'BBD', 'value' => 'Barbados Dollar'],
    'BYN' => ['id' => 'BYN', 'value' => 'Belarusian Ruble'],
    'BZD' => ['id' => 'BZD', 'value' => 'Belize Dollar'],
    'XOF' => ['id' => 'XOF', 'value' => 'CFA Franc BCEAO'],
    'BMD' => ['id' => 'BMD', 'value' => 'Bermudian Dollar'],
    'INR' => ['id' => 'INR', 'value' => 'Indian Rupee'],
    'BTN' => ['id' => 'BTN', 'value' => 'Ngultrum'],
    'BOB' => ['id' => 'BOB', 'value' => 'Boliviano'],
    'BOV' => ['id' => 'BOV', 'value' => 'Mvdol'],
    'BAM' => ['id' => 'BAM', 'value' => 'Convertible Mark'],
    'BWP' => ['id' => 'BWP', 'value' => 'Pula'],
    'NOK' => ['id' => 'NOK', 'value' => 'Norwegian Krone'],
    'BRL' => ['id' => 'BRL', 'value' => 'Brazilian Real'],
    'BND' => ['id' => 'BND', 'value' => 'Brunei Dollar'],
    'BGN' => ['id' => 'BGN', 'value' => 'Bulgarian Lev'],
    'BIF' => ['id' => 'BIF', 'value' => 'Burundi Franc'],
    'CVE' => ['id' => 'CVE', 'value' => 'Cabo Verde Escudo'],
    'KHR' => ['id' => 'KHR', 'value' => 'Riel'],
    'XAF' => ['id' => 'XAF', 'value' => 'CFA Franc BEAC'],
    'CAD' => ['id' => 'CAD', 'value' => 'Canadian Dollar'],
    'KYD' => ['id' => 'KYD', 'value' => 'Cayman Islands Dollar'],
    'CLP' => ['id' => 'CLP', 'value' => 'Chilean Peso'],
    'CLF' => ['id' => 'CLF', 'value' => 'Unidad de Fomento'],
    'CNY' => ['id' => 'CNY', 'value' => 'Yuan Renminbi'],
    'COP' => ['id' => 'COP', 'value' => 'Colombian Peso'],
    'COU' => ['id' => 'COU', 'value' => 'Unidad de Valor Real'],
    'KMF' => ['id' => 'KMF', 'value' => 'Comorian Franc '],
    'CDF' => ['id' => 'CDF', 'value' => 'Congolese Franc'],
    'NZD' => ['id' => 'NZD', 'value' => 'New Zealand Dollar'],
    'CRC' => ['id' => 'CRC', 'value' => 'Costa Rican Colon'],
    'HRK' => ['id' => 'HRK', 'value' => 'Kuna'],
    'CUP' => ['id' => 'CUP', 'value' => 'Cuban Peso'],
    'CUC' => ['id' => 'CUC', 'value' => 'Peso Convertible'],
    'ANG' => ['id' => 'ANG', 'value' => 'Netherlands Antillean Guilder'],
    'CZK' => ['id' => 'CZK', 'value' => 'Czech Koruna'],
    'DKK' => ['id' => 'DKK', 'value' => 'Danish Krone'],
    'DJF' => ['id' => 'DJF', 'value' => 'Djibouti Franc'],
    'DOP' => ['id' => 'DOP', 'value' => 'Dominican Peso'],
    'EGP' => ['id' => 'EGP', 'value' => 'Egyptian Pound'],
    'SVC' => ['id' => 'SVC', 'value' => 'El Salvador Colon'],
    'ERN' => ['id' => 'ERN', 'value' => 'Nakfa'],
    'ETB' => ['id' => 'ETB', 'value' => 'Ethiopian Birr'],
    'FKP' => ['id' => 'FKP', 'value' => 'Falkland Islands Pound'],
    'FJD' => ['id' => 'FJD', 'value' => 'Fiji Dollar'],
    'XPF' => ['id' => 'XPF', 'value' => 'CFP Franc'],
    'GMD' => ['id' => 'GMD', 'value' => 'Dalasi'],
    'GEL' => ['id' => 'GEL', 'value' => 'Lari'],
    'GHS' => ['id' => 'GHS', 'value' => 'Ghana Cedi'],
    'GIP' => ['id' => 'GIP', 'value' => 'Gibraltar Pound'],
    'GTQ' => ['id' => 'GTQ', 'value' => 'Quetzal'],
    'GBP' => ['id' => 'GBP', 'value' => 'Pound Sterling'],
    'GNF' => ['id' => 'GNF', 'value' => 'Guinean Franc'],
    'GYD' => ['id' => 'GYD', 'value' => 'Guyana Dollar'],
    'HTG' => ['id' => 'HTG', 'value' => 'Gourde'],
    'HNL' => ['id' => 'HNL', 'value' => 'Lempira'],
    'HKD' => ['id' => 'HKD', 'value' => 'Hong Kong Dollar'],
    'HUF' => ['id' => 'HUF', 'value' => 'Forint'],
    'ISK' => ['id' => 'ISK', 'value' => 'Iceland Krona'],
    'IDR' => ['id' => 'IDR', 'value' => 'Rupiah'],
    'XDR' => ['id' => 'XDR', 'value' => 'SDR (Special Drawing Right)'],
    'IRR' => ['id' => 'IRR', 'value' => 'Iranian Rial'],
    'IQD' => ['id' => 'IQD', 'value' => 'Iraqi Dinar'],
    'ILS' => ['id' => 'ILS', 'value' => 'New Israeli Sheqel'],
    'JMD' => ['id' => 'JMD', 'value' => 'Jamaican Dollar'],
    'JPY' => ['id' => 'JPY', 'value' => 'Yen'],
    'JOD' => ['id' => 'JOD', 'value' => 'Jordanian Dinar'],
    'KZT' => ['id' => 'KZT', 'value' => 'Tenge'],
    'KES' => ['id' => 'KES', 'value' => 'Kenyan Shilling'],
    'KPW' => ['id' => 'KPW', 'value' => 'North Korean Won'],
    'KRW' => ['id' => 'KRW', 'value' => 'Won'],
    'KWD' => ['id' => 'KWD', 'value' => 'Kuwaiti Dinar'],
    'KGS' => ['id' => 'KGS', 'value' => 'Som'],
    'LAK' => ['id' => 'LAK', 'value' => 'Lao Kip'],
    'LBP' => ['id' => 'LBP', 'value' => 'Lebanese Pound'],
    'LSL' => ['id' => 'LSL', 'value' => 'Loti'],
    'ZAR' => ['id' => 'ZAR', 'value' => 'Rand'],
    'LRD' => ['id' => 'LRD', 'value' => 'Liberian Dollar'],
    'LYD' => ['id' => 'LYD', 'value' => 'Libyan Dinar'],
    'CHF' => ['id' => 'CHF', 'value' => 'Swiss Franc'],
    'MOP' => ['id' => 'MOP', 'value' => 'Pataca'],
    'MKD' => ['id' => 'MKD', 'value' => 'Denar'],
    'MGA' => ['id' => 'MGA', 'value' => 'Malagasy Ariary'],
    'MWK' => ['id' => 'MWK', 'value' => 'Malawi Kwacha'],
    'MYR' => ['id' => 'MYR', 'value' => 'Malaysian Ringgit'],
    'MVR' => ['id' => 'MVR', 'value' => 'Rufiyaa'],
    'MRU' => ['id' => 'MRU', 'value' => 'Ouguiya'],
    'MUR' => ['id' => 'MUR', 'value' => 'Mauritius Rupee'],
    'XUA' => ['id' => 'XUA', 'value' => 'ADB Unit of Account'],
    'MXN' => ['id' => 'MXN', 'value' => 'Mexican Peso'],
    'MXV' => ['id' => 'MXV', 'value' => 'Mexican Unidad de Inversion (UDI)'],
    'MDL' => ['id' => 'MDL', 'value' => 'Moldovan Leu'],
    'MNT' => ['id' => 'MNT', 'value' => 'Tugrik'],
    'MAD' => ['id' => 'MAD', 'value' => 'Moroccan Dirham'],
    'MZN' => ['id' => 'MZN', 'value' => 'Mozambique Metical'],
    'MMK' => ['id' => 'MMK', 'value' => 'Kyat'],
    'NAD' => ['id' => 'NAD', 'value' => 'Namibia Dollar'],
    'NPR' => ['id' => 'NPR', 'value' => 'Nepalese Rupee'],
    'NIO' => ['id' => 'NIO', 'value' => 'Cordoba Oro'],
    'NGN' => ['id' => 'NGN', 'value' => 'Naira'],
    'OMR' => ['id' => 'OMR', 'value' => 'Rial Omani'],
    'PKR' => ['id' => 'PKR', 'value' => 'Pakistan Rupee'],
    'PAB' => ['id' => 'PAB', 'value' => 'Balboa'],
    'PGK' => ['id' => 'PGK', 'value' => 'Kina'],
    'PYG' => ['id' => 'PYG', 'value' => 'Guarani'],
    'PEN' => ['id' => 'PEN', 'value' => 'Sol'],
    'PHP' => ['id' => 'PHP', 'value' => 'Philippine Piso'],
    'PLN' => ['id' => 'PLN', 'value' => 'Zloty'],
    'QAR' => ['id' => 'QAR', 'value' => 'Qatari Rial'],
    'RON' => ['id' => 'RON', 'value' => 'Romanian Leu'],
    'RUB' => ['id' => 'RUB', 'value' => 'Russian Ruble'],
    'RWF' => ['id' => 'RWF', 'value' => 'Rwanda Franc'],
    'SHP' => ['id' => 'SHP', 'value' => 'Saint Helena Pound'],
    'WST' => ['id' => 'WST', 'value' => 'Tala'],
    'STN' => ['id' => 'STN', 'value' => 'Dobra'],
    'SAR' => ['id' => 'SAR', 'value' => 'Saudi Riyal'],
    'RSD' => ['id' => 'RSD', 'value' => 'Serbian Dinar'],
    'SCR' => ['id' => 'SCR', 'value' => 'Seychelles Rupee'],
    'SLL' => ['id' => 'SLL', 'value' => 'Leone'],
    'SGD' => ['id' => 'SGD', 'value' => 'Singapore Dollar'],
    'XSU' => ['id' => 'XSU', 'value' => 'Sucre'],
    'SBD' => ['id' => 'SBD', 'value' => 'Solomon Islands Dollar'],
    'SOS' => ['id' => 'SOS', 'value' => 'Somali Shilling'],
    'SSP' => ['id' => 'SSP', 'value' => 'South Sudanese Pound'],
    'LKR' => ['id' => 'LKR', 'value' => 'Sri Lanka Rupee'],
    'SDG' => ['id' => 'SDG', 'value' => 'Sudanese Pound'],
    'SRD' => ['id' => 'SRD', 'value' => 'Surinam Dollar'],
    'SZL' => ['id' => 'SZL', 'value' => 'Lilangeni'],
    'SEK' => ['id' => 'SEK', 'value' => 'Swedish Krona'],
    'CHE' => ['id' => 'CHE', 'value' => 'WIR Euro'],
    'CHW' => ['id' => 'CHW', 'value' => 'WIR Franc'],
    'SYP' => ['id' => 'SYP', 'value' => 'Syrian Pound'],
    'TWD' => ['id' => 'TWD', 'value' => 'New Taiwan Dollar'],
    'TJS' => ['id' => 'TJS', 'value' => 'Somoni'],
    'TZS' => ['id' => 'TZS', 'value' => 'Tanzanian Shilling'],
    'THB' => ['id' => 'THB', 'value' => 'Baht'],
    'TOP' => ['id' => 'TOP', 'value' => 'Pa’anga'],
    'TTD' => ['id' => 'TTD', 'value' => 'Trinidad and Tobago Dollar'],
    'TND' => ['id' => 'TND', 'value' => 'Tunisian Dinar'],
    'TRY' => ['id' => 'TRY', 'value' => 'Turkish Lira'],
    'TMT' => ['id' => 'TMT', 'value' => 'Turkmenistan New Manat'],
    'UGX' => ['id' => 'UGX', 'value' => 'Uganda Shilling'],
    'UAH' => ['id' => 'UAH', 'value' => 'Hryvnia'],
    'AED' => ['id' => 'AED', 'value' => 'UAE Dirham'],
    'USN' => ['id' => 'USN', 'value' => 'US Dollar (Next day)'],
    'UYU' => ['id' => 'UYU', 'value' => 'Peso Uruguayo'],
    'UYI' => ['id' => 'UYI', 'value' => 'Uruguay Peso en Unidades Indexadas (URUIURUI)'],
    'UZS' => ['id' => 'UZS', 'value' => 'Uzbekistan Sum'],
    'VUV' => ['id' => 'VUV', 'value' => 'Vatu'],
    'VEF' => ['id' => 'VEF', 'value' => 'Bolívar'],
    'VND' => ['id' => 'VND', 'value' => 'Dong'],
    'YER' => ['id' => 'YER', 'value' => 'Yemeni Rial'],
    'ZMW' => ['id' => 'ZMW', 'value' => 'Zambian Kwacha'],
    'ZWL' => ['id' => 'ZWL', 'value' => 'Zimbabwe Dollar'],
    'XBA' => ['id' => 'XBA', 'value' => 'Bond Markets Unit European Composite Unit (EURCO)'],
    'XBB' => ['id' => 'XBB', 'value' => 'Bond Markets Unit European Monetary Unit (E.M.U.-6)'],
    'XBC' => ['id' => 'XBC', 'value' => 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)'],
    'XBD' => ['id' => 'XBD', 'value' => 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)'],
    'XTS' => ['id' => 'XTS', 'value' => 'Codes specifically reserved for testing purposes'],
    'XXX' => ['id' => 'XXX', 'value' => 'The codes assigned for transactions where no currency is involved'],
    'XAU' => ['id' => 'XAU', 'value' => 'Gold'],
    'XPD' => ['id' => 'XPD', 'value' => 'Palladium'],
    'XPT' => ['id' => 'XPT', 'value' => 'Platinum'],
    'XAG' => ['id' => 'XAG', 'value' => 'Silver']
];
