<?php

//Catálogo N° 55:

return [
    '3001' => ['id' => '3001', 'value' => 'Detracciones: Recursos Hidrobiológicos-Matrícula de la embarcación'],
    '3002' => ['id' => '3002', 'value' => 'Detracciones: Recursos Hidrobiológicos-Nombre de la embarcación'],
    '3003' => ['id' => '3003', 'value' => 'Detracciones: Recursos Hidrobiológicos-Tipo de especie vendida'],
    '3004' => ['id' => '3004', 'value' => 'Detracciones: Recursos Hidrobiológicos-Lugar de descarga'],
    '3005' => ['id' => '3005', 'value' => 'Detracciones: Recursos Hidrobiológicos-Fecha de descarga'],
    '3006' => ['id' => '3006', 'value' => 'Detracciones: Recursos Hidrobiológicos-Cantidad de especie vendida'],
    '3050' => ['id' => '3050', 'value' => 'Transportre Terreste - Número de asiento'],
    '3051' => ['id' => '3051', 'value' => 'Transporte Terrestre - Información de manifiesto de pasajeros'],
    '3052' => ['id' => '3052', 'value' => 'Transporte Terrestre - Número de documento de identidad del pasajero'],
    '3053' => ['id' => '3053', 'value' => 'Transporte Terrestre - Tipo de documento de identidad del pasajero'],
    '3054' => ['id' => '3054', 'value' => 'Transporte Terrestre - Nombres y apellidos del pasajero'],
    '3055' => ['id' => '3055', 'value' => 'Transporte Terrestre - Ciudad o lugar de destino - Ubigeo'],
    '3056' => ['id' => '3056', 'value' => 'Transporte Terrestre - Ciudad o lugar de destino - Dirección detallada'],
    '3057' => ['id' => '3057', 'value' => 'Transporte Terrestre - Ciudad o lugar de origen - Ubigeo'],
    '3058' => ['id' => '3058', 'value' => 'Transporte Terrestre - Ciudad o lugar de origen - Dirección detallada'],
    '3059' => ['id' => '3059', 'value' => 'Transporte Terrestre - Fecha de inicio programado'],
    '3060' => ['id' => '3060', 'value' => 'Transporte Terrestre - Hora de inicio programado'],
    '4000' => ['id' => '4000', 'value' => 'Beneficio Hospedajes: Código de país de emisión del pasaporte'],
    '4001' => ['id' => '4001', 'value' => 'Beneficio Hospedajes: Código de país de residencia del sujeto no domiciliado'],
    '4002' => ['id' => '4002', 'value' => 'Beneficio Hospedajes: Fecha de ingreso al país'],
    '4003' => ['id' => '4003', 'value' => 'Beneficio Hospedajes: Fecha de Ingreso al Establecimiento'],
    '4004' => ['id' => '4004', 'value' => 'Beneficio Hospedajes: Fecha de Salida del Establecimiento'],
    '4005' => ['id' => '4005', 'value' => 'Beneficio Hospedajes: Número de Días de Permanencia'],
    '4006' => ['id' => '4006', 'value' => 'Beneficio Hospedajes: Fecha de Consumo '],
    '4007' => ['id' => '4007', 'value' => 'Beneficio Hospedajes: Nombres y apellidos del huesped '],
    '4008' => ['id' => '4008', 'value' => 'Beneficio Hospedajes: Tipo de documento de identidad del huesped '],
    '4009' => ['id' => '4009', 'value' => 'Beneficio Hospedajes: Número de documento de identidad del huesped '],
    '4030' => ['id' => '4030', 'value' => 'Carta Porte Aéreo:  Lugar de origen - Código de ubigeo'],
    '4031' => ['id' => '4031', 'value' => 'Carta Porte Aéreo:  Lugar de origen - Dirección detallada'],
    '4032' => ['id' => '4032', 'value' => 'Carta Porte Aéreo:  Lugar de destino - Código de ubigeo'],
    '4033' => ['id' => '4033', 'value' => 'Carta Porte Aéreo:  Lugar de destino - Dirección detallada'],
    '4040' => ['id' => '4040', 'value' => 'BVME transporte ferroviario: Pasajero - Apellidos y Nombres'],
    '4041' => ['id' => '4041', 'value' => 'BVME transporte ferroviario: Pasajero - Tipo documento de identidad'],
    '4042' => ['id' => '4042', 'value' => 'BVME transporte ferroviario: Servicio transporte: Ciudad o lugar de origen - Código de ubigeo'],
    '4043' => ['id' => '4043', 'value' => 'BVME transporte ferroviario: Servicio transporte: Ciudad o lugar de origen - Dirección detallada'],
    '4044' => ['id' => '4044', 'value' => 'BVME transporte ferroviario: Servicio transporte: Ciudad o lugar de destino - Código de ubigeo'],
    '4045' => ['id' => '4045', 'value' => 'BVME transporte ferroviario: Servicio transporte: Ciudad o lugar de destino - Dirección detallada'],
    '4046' => ['id' => '4046', 'value' => 'BVME transporte ferroviario: Servicio transporte:Número de asiento'],
    '4047' => ['id' => '4047', 'value' => 'BVME transporte ferroviario: Servicio transporte: Hora programada de inicio de viaje'],
    '4048' => ['id' => '4048', 'value' => 'BVME transporte ferroviario: Servicio transporte: Fecha programada de inicio de viaje'],
    '4049' => ['id' => '4049', 'value' => 'BVME transporte ferroviario: Pasajero - número de documento de identidad'],
    '4060' => ['id' => '4060', 'value' => 'Regalía Petrolera: Decreto Supremo de aprobación del contrato'],
    '4061' => ['id' => '4061', 'value' => 'Regalía Petrolera: Area de contrato (Lote)'],
    '4062' => ['id' => '4062', 'value' => 'Regalía Petrolera: Periodo de pago - Fecha de inicio'],
    '4063' => ['id' => '4063', 'value' => 'Regalía Petrolera: Periodo de pago - Fecha de fin'],
    '4064' => ['id' => '4064', 'value' => 'Regalía Petrolera: Fecha de Pago'],
    '5000' => ['id' => '5000', 'value' => 'Proveedores Estado: Número de Expediente'],
    '5001' => ['id' => '5001', 'value' => 'Proveedores Estado: Código de Unidad Ejecutora'],
    '5002' => ['id' => '5002', 'value' => 'Proveedores Estado: N° de Proceso de Selección'],
    '5003' => ['id' => '5003', 'value' => 'Proveedores Estado: N° de Contrato'],
    '6000' => ['id' => '6000', 'value' => 'Comercialización de Oro:  Código Unico Concesión Minera'],
    '6001' => ['id' => '6001', 'value' => 'Comercialización de Oro:  N° declaración compromiso'],
    '6002' => ['id' => '6002', 'value' => 'Comercialización de Oro:  N° Reg. Especial .Comerci. Oro'],
    '6003' => ['id' => '6003', 'value' => 'Comercialización de Oro:  N° Resolución que autoriza Planta de Beneficio'],
    '6004' => ['id' => '6004', 'value' => 'Comercialización de Oro: Ley Mineral (% concent. oro)'],
    '7000' => ['id' => '7000', 'value' => 'Gastos Art. 37 Renta:  Número de Placa'],
    '7001' => ['id' => '7001', 'value' => 'Créditos Hipotecarios: Tipo de préstamo'],
    '7002' => ['id' => '7002', 'value' => 'Créditos Hipotecarios: Indicador de Primera Vivienda'],
    '7003' => ['id' => '7003', 'value' => 'Créditos Hipotecarios: Partida Registral'],
    '7004' => ['id' => '7004', 'value' => 'Créditos Hipotecarios: Número de contrato'],
    '7005' => ['id' => '7005', 'value' => 'Créditos Hipotecarios: Fecha de otorgamiento del crédito'],
    '7006' => ['id' => '7006', 'value' => 'Créditos Hipotecarios: Dirección del predio - Código de ubigeo'],
    '7007' => ['id' => '7007', 'value' => 'Créditos Hipotecarios: Dirección del predio - Dirección completa'],
    '7008' => ['id' => '7008', 'value' => 'Créditos Hipotecarios: Dirección del predio - Urbanización'],
    '7009' => ['id' => '7009', 'value' => 'Créditos Hipotecarios: Dirección del predio - Provincia'],
    '7010' => ['id' => '7010', 'value' => 'Créditos Hipotecarios: Dirección del predio - Distrito']
];
