<?php

//Catálogo N° 4:

return [
    'AF' => ['id' => 'AF', 'value' => 'Afghanistan'],
    'AX' => ['id' => 'AX', 'value' => 'Åland Islands'],
    'AL' => ['id' => 'AL', 'value' => 'Albania'],
    'DZ' => ['id' => 'DZ', 'value' => 'Algeria'],
    'AS' => ['id' => 'AS', 'value' => 'American Samoa'],
    'AD' => ['id' => 'AD', 'value' => 'Andorra'],
    'AO' => ['id' => 'AO', 'value' => 'Angola'],
    'AI' => ['id' => 'AI', 'value' => 'Anguilla'],
    'AQ' => ['id' => 'AQ', 'value' => 'Antarctica'],
    'AG' => ['id' => 'AG', 'value' => 'Antigua and Barbuda'],
    'AR' => ['id' => 'AR', 'value' => 'Argentina'],
    'AM' => ['id' => 'AM', 'value' => 'Armenia'],
    'AW' => ['id' => 'AW', 'value' => 'Aruba'],
    'AU' => ['id' => 'AU', 'value' => 'Australia'],
    'AT' => ['id' => 'AT', 'value' => 'Austria'],
    'AZ' => ['id' => 'AZ', 'value' => 'Azerbaijan'],
    'BS' => ['id' => 'BS', 'value' => 'Bahamas (the)'],
    'BH' => ['id' => 'BH', 'value' => 'Bahrain'],
    'BD' => ['id' => 'BD', 'value' => 'Bangladesh'],
    'BB' => ['id' => 'BB', 'value' => 'Barbados'],
    'BY' => ['id' => 'BY', 'value' => 'Belarus'],
    'BE' => ['id' => 'BE', 'value' => 'Belgium'],
    'BZ' => ['id' => 'BZ', 'value' => 'Belize'],
    'BJ' => ['id' => 'BJ', 'value' => 'Benin'],
    'BM' => ['id' => 'BM', 'value' => 'Bermuda'],
    'BT' => ['id' => 'BT', 'value' => 'Bhutan'],
    'BO' => ['id' => 'BO', 'value' => 'Bolivia (Plurinational State of)'],
    'BQ' => ['id' => 'BQ', 'value' => 'Bonaire, Sint Eustatius and Saba'],
    'BA' => ['id' => 'BA', 'value' => 'Bosnia and Herzegovina'],
    'BW' => ['id' => 'BW', 'value' => 'Botswana'],
    'BV' => ['id' => 'BV', 'value' => 'Bouvet Island'],
    'BR' => ['id' => 'BR', 'value' => 'Brazil'],
    'IO' => ['id' => 'IO', 'value' => 'British Indian Ocean Territory (the)'],
    'BN' => ['id' => 'BN', 'value' => 'Brunei Darussalam'],
    'BG' => ['id' => 'BG', 'value' => 'Bulgaria'],
    'BF' => ['id' => 'BF', 'value' => 'Burkina Faso'],
    'BI' => ['id' => 'BI', 'value' => 'Burundi'],
    'CV' => ['id' => 'CV', 'value' => 'Cabo Verde'],
    'KH' => ['id' => 'KH', 'value' => 'Cambodia'],
    'CM' => ['id' => 'CM', 'value' => 'Cameroon'],
    'CA' => ['id' => 'CA', 'value' => 'Canada'],
    'KY' => ['id' => 'KY', 'value' => 'Cayman Islands (the)'],
    'CF' => ['id' => 'CF', 'value' => 'Central African Republic (the)'],
    'TD' => ['id' => 'TD', 'value' => 'Chad'],
    'CL' => ['id' => 'CL', 'value' => 'Chile'],
    'CN' => ['id' => 'CN', 'value' => 'China'],
    'CX' => ['id' => 'CX', 'value' => 'Christmas Island'],
    'CC' => ['id' => 'CC', 'value' => 'Cocos (Keeling) Islands (the)'],
    'CO' => ['id' => 'CO', 'value' => 'Colombia'],
    'KM' => ['id' => 'KM', 'value' => 'Comoros (the)'],
    'CD' => ['id' => 'CD', 'value' => 'Congo (the Democratic Republic of the)'],
    'CG' => ['id' => 'CG', 'value' => 'Congo (the)'],
    'CK' => ['id' => 'CK', 'value' => 'Cook Islands (the)'],
    'CR' => ['id' => 'CR', 'value' => 'Costa Rica'],
    'CI' => ['id' => 'CI', 'value' => "Côte d'Ivoire"],
    'HR' => ['id' => 'HR', 'value' => 'Croatia'],
    'CU' => ['id' => 'CU', 'value' => 'Cuba'],
    'CW' => ['id' => 'CW', 'value' => 'Curaçao'],
    'CY' => ['id' => 'CY', 'value' => 'Cyprus'],
    'CZ' => ['id' => 'CZ', 'value' => 'Czechia'],
    'DK' => ['id' => 'DK', 'value' => 'Denmark'],
    'DJ' => ['id' => 'DJ', 'value' => 'Djibouti'],
    'DM' => ['id' => 'DM', 'value' => 'Dominica'],
    'DO' => ['id' => 'DO', 'value' => 'Dominican Republic (the)'],
    'EC' => ['id' => 'EC', 'value' => 'Ecuador'],
    'EG' => ['id' => 'EG', 'value' => 'Egypt'],
    'SV' => ['id' => 'SV', 'value' => 'El Salvador'],
    'GQ' => ['id' => 'GQ', 'value' => 'Equatorial Guinea'],
    'ER' => ['id' => 'ER', 'value' => 'Eritrea'],
    'EE' => ['id' => 'EE', 'value' => 'Estonia'],
    'ET' => ['id' => 'ET', 'value' => 'Ethiopia'],
    'FK' => ['id' => 'FK', 'value' => 'Falkland Islands (the) [Malvinas]'],
    'FO' => ['id' => 'FO', 'value' => 'Faroe Islands (the)'],
    'FJ' => ['id' => 'FJ', 'value' => 'Fiji'],
    'FI' => ['id' => 'FI', 'value' => 'Finland'],
    'FR' => ['id' => 'FR', 'value' => 'France'],
    'GF' => ['id' => 'GF', 'value' => 'French Guiana'],
    'PF' => ['id' => 'PF', 'value' => 'French Polynesia'],
    'TF' => ['id' => 'TF', 'value' => 'French Southern Territories (the)'],
    'GA' => ['id' => 'GA', 'value' => 'Gabon'],
    'GM' => ['id' => 'GM', 'value' => 'Gambia (the)'],
    'GE' => ['id' => 'GE', 'value' => 'Georgia'],
    'DE' => ['id' => 'DE', 'value' => 'Germany'],
    'GH' => ['id' => 'GH', 'value' => 'Ghana'],
    'GI' => ['id' => 'GI', 'value' => 'Gibraltar'],
    'GR' => ['id' => 'GR', 'value' => 'Greece'],
    'GL' => ['id' => 'GL', 'value' => 'Greenland'],
    'GD' => ['id' => 'GD', 'value' => 'Grenada'],
    'GP' => ['id' => 'GP', 'value' => 'Guadeloupe'],
    'GU' => ['id' => 'GU', 'value' => 'Guam'],
    'GT' => ['id' => 'GT', 'value' => 'Guatemala'],
    'GG' => ['id' => 'GG', 'value' => 'Guernsey'],
    'GN' => ['id' => 'GN', 'value' => 'Guinea'],
    'GW' => ['id' => 'GW', 'value' => 'Guinea-Bissau'],
    'GY' => ['id' => 'GY', 'value' => 'Guyana'],
    'HT' => ['id' => 'HT', 'value' => 'Haiti'],
    'HM' => ['id' => 'HM', 'value' => 'Heard Island and McDonald Islands'],
    'VA' => ['id' => 'VA', 'value' => 'Holy See (the)'],
    'HN' => ['id' => 'HN', 'value' => 'Honduras'],
    'HK' => ['id' => 'HK', 'value' => 'Hong Kong'],
    'HU' => ['id' => 'HU', 'value' => 'Hungary'],
    'IS' => ['id' => 'IS', 'value' => 'Iceland'],
    'IN' => ['id' => 'IN', 'value' => 'India'],
    'ID' => ['id' => 'ID', 'value' => 'Indonesia'],
    'IR' => ['id' => 'IR', 'value' => 'Iran (Islamic Republic of)'],
    'IQ' => ['id' => 'IQ', 'value' => 'Iraq'],
    'IE' => ['id' => 'IE', 'value' => 'Ireland'],
    'IM' => ['id' => 'IM', 'value' => 'Isle of Man'],
    'IL' => ['id' => 'IL', 'value' => 'Israel'],
    'IT' => ['id' => 'IT', 'value' => 'Italy'],
    'JM' => ['id' => 'JM', 'value' => 'Jamaica'],
    'JP' => ['id' => 'JP', 'value' => 'Japan'],
    'JE' => ['id' => 'JE', 'value' => 'Jersey'],
    'JO' => ['id' => 'JO', 'value' => 'Jordan'],
    'KZ' => ['id' => 'KZ', 'value' => 'Kazakhstan'],
    'KE' => ['id' => 'KE', 'value' => 'Kenya'],
    'KI' => ['id' => 'KI', 'value' => 'Kiribati'],
    'KP' => ['id' => 'KP', 'value' => "Korea (the Democratic People's Republic of)"],
    'KR' => ['id' => 'KR', 'value' => 'Korea (the Republic of)'],
    'KW' => ['id' => 'KW', 'value' => 'Kuwait'],
    'KG' => ['id' => 'KG', 'value' => 'Kyrgyzstan'],
    'LA' => ['id' => 'LA', 'value' => "Lao People's Democratic Republic (the)"],
    'LV' => ['id' => 'LV', 'value' => 'Latvia'],
    'LB' => ['id' => 'LB', 'value' => 'Lebanon'],
    'LS' => ['id' => 'LS', 'value' => 'Lesotho'],
    'LR' => ['id' => 'LR', 'value' => 'Liberia'],
    'LY' => ['id' => 'LY', 'value' => 'Libya'],
    'LI' => ['id' => 'LI', 'value' => 'Liechtenstein'],
    'LT' => ['id' => 'LT', 'value' => 'Lithuania'],
    'LU' => ['id' => 'LU', 'value' => 'Luxembourg'],
    'MO' => ['id' => 'MO', 'value' => 'Macao'],
    'MK' => ['id' => 'MK', 'value' => 'Macedonia (the former Yugoslav Republic of)'],
    'MG' => ['id' => 'MG', 'value' => 'Madagascar'],
    'MW' => ['id' => 'MW', 'value' => 'Malawi'],
    'MY' => ['id' => 'MY', 'value' => 'Malaysia'],
    'MV' => ['id' => 'MV', 'value' => 'Maldives'],
    'ML' => ['id' => 'ML', 'value' => 'Mali'],
    'MT' => ['id' => 'MT', 'value' => 'Malta'],
    'MH' => ['id' => 'MH', 'value' => 'Marshall Islands (the)'],
    'MQ' => ['id' => 'MQ', 'value' => 'Martinique'],
    'MR' => ['id' => 'MR', 'value' => 'Mauritania'],
    'MU' => ['id' => 'MU', 'value' => 'Mauritius'],
    'YT' => ['id' => 'YT', 'value' => 'Mayotte'],
    'MX' => ['id' => 'MX', 'value' => 'Mexico'],
    'FM' => ['id' => 'FM', 'value' => 'Micronesia (Federated States of)'],
    'MD' => ['id' => 'MD', 'value' => 'Moldova (the Republic of)'],
    'MC' => ['id' => 'MC', 'value' => 'Monaco'],
    'MN' => ['id' => 'MN', 'value' => 'Mongolia'],
    'ME' => ['id' => 'ME', 'value' => 'Montenegro'],
    'MS' => ['id' => 'MS', 'value' => 'Montserrat'],
    'MA' => ['id' => 'MA', 'value' => 'Morocco'],
    'MZ' => ['id' => 'MZ', 'value' => 'Mozambique'],
    'MM' => ['id' => 'MM', 'value' => 'Myanmar'],
    'NA' => ['id' => 'NA', 'value' => 'Namibia'],
    'NR' => ['id' => 'NR', 'value' => 'Nauru'],
    'NP' => ['id' => 'NP', 'value' => 'Nepal'],
    'NL' => ['id' => 'NL', 'value' => 'Netherlands (the)'],
    'NC' => ['id' => 'NC', 'value' => 'New Caledonia'],
    'NZ' => ['id' => 'NZ', 'value' => 'New Zealand'],
    'NI' => ['id' => 'NI', 'value' => 'Nicaragua'],
    'NE' => ['id' => 'NE', 'value' => 'Niger (the)'],
    'NG' => ['id' => 'NG', 'value' => 'Nigeria'],
    'NU' => ['id' => 'NU', 'value' => 'Niue'],
    'NF' => ['id' => 'NF', 'value' => 'Norfolk Island'],
    'MP' => ['id' => 'MP', 'value' => 'Northern Mariana Islands (the)'],
    'NO' => ['id' => 'NO', 'value' => 'Norway'],
    'OM' => ['id' => 'OM', 'value' => 'Oman'],
    'PK' => ['id' => 'PK', 'value' => 'Pakistan'],
    'PW' => ['id' => 'PW', 'value' => 'Palau'],
    'PS' => ['id' => 'PS', 'value' => 'Palestine, State of'],
    'PA' => ['id' => 'PA', 'value' => 'Panama'],
    'PG' => ['id' => 'PG', 'value' => 'Papua New Guinea'],
    'PY' => ['id' => 'PY', 'value' => 'Paraguay'],
    'PE' => ['id' => 'PE', 'value' => 'Peru'],
    'PH' => ['id' => 'PH', 'value' => 'Philippines (the)'],
    'PN' => ['id' => 'PN', 'value' => 'Pitcairn'],
    'PL' => ['id' => 'PL', 'value' => 'Poland'],
    'PT' => ['id' => 'PT', 'value' => 'Portugal'],
    'PR' => ['id' => 'PR', 'value' => 'Puerto Rico'],
    'QA' => ['id' => 'QA', 'value' => 'Qatar'],
    'RE' => ['id' => 'RE', 'value' => 'Réunion'],
    'RO' => ['id' => 'RO', 'value' => 'Romania'],
    'RU' => ['id' => 'RU', 'value' => 'Russian Federation (the)'],
    'RW' => ['id' => 'RW', 'value' => 'Rwanda'],
    'BL' => ['id' => 'BL', 'value' => 'Saint Barthélemy'],
    'SH' => ['id' => 'SH', 'value' => 'Saint Helena, Ascension and Tristan da Cunha'],
    'KN' => ['id' => 'KN', 'value' => 'Saint Kitts and Nevis'],
    'LC' => ['id' => 'LC', 'value' => 'Saint Lucia'],
    'MF' => ['id' => 'MF', 'value' => 'Saint Martin (French part)'],
    'PM' => ['id' => 'PM', 'value' => 'Saint Pierre and Miquelon'],
    'VC' => ['id' => 'VC', 'value' => 'Saint Vincent and the Grenadines'],
    'WS' => ['id' => 'WS', 'value' => 'Samoa'],
    'SM' => ['id' => 'SM', 'value' => 'San Marino'],
    'ST' => ['id' => 'ST', 'value' => 'Sao Tome and Principe'],
    'SA' => ['id' => 'SA', 'value' => 'Saudi Arabia'],
    'SN' => ['id' => 'SN', 'value' => 'Senegal'],
    'RS' => ['id' => 'RS', 'value' => 'Serbia'],
    'SC' => ['id' => 'SC', 'value' => 'Seychelles'],
    'SL' => ['id' => 'SL', 'value' => 'Sierra Leone'],
    'SG' => ['id' => 'SG', 'value' => 'Singapore'],
    'SX' => ['id' => 'SX', 'value' => 'Sint Maarten (Dutch part)'],
    'SK' => ['id' => 'SK', 'value' => 'Slovakia'],
    'SI' => ['id' => 'SI', 'value' => 'Slovenia'],
    'SB' => ['id' => 'SB', 'value' => 'Solomon Islands'],
    'SO' => ['id' => 'SO', 'value' => 'Somalia'],
    'ZA' => ['id' => 'ZA', 'value' => 'South Africa'],
    'GS' => ['id' => 'GS', 'value' => 'South Georgia and the South Sandwich Islands'],
    'SS' => ['id' => 'SS', 'value' => 'South Sudan'],
    'ES' => ['id' => 'ES', 'value' => 'Spain'],
    'LK' => ['id' => 'LK', 'value' => 'Sri Lanka'],
    'SD' => ['id' => 'SD', 'value' => 'Sudan (the)'],
    'SR' => ['id' => 'SR', 'value' => 'Suriname'],
    'SJ' => ['id' => 'SJ', 'value' => 'Svalbard and Jan Mayen'],
    'SZ' => ['id' => 'SZ', 'value' => 'Swaziland'],
    'SE' => ['id' => 'SE', 'value' => 'Sweden'],
    'CH' => ['id' => 'CH', 'value' => 'Switzerland'],
    'SY' => ['id' => 'SY', 'value' => 'Syrian Arab Republic'],
    'TW' => ['id' => 'TW', 'value' => 'Taiwan (Province of China)'],
    'TJ' => ['id' => 'TJ', 'value' => 'Tajikistan'],
    'TZ' => ['id' => 'TZ', 'value' => 'Tanzania, United Republic of'],
    'TH' => ['id' => 'TH', 'value' => 'Thailand'],
    'TL' => ['id' => 'TL', 'value' => 'Timor-Leste'],
    'TG' => ['id' => 'TG', 'value' => 'Togo'],
    'TK' => ['id' => 'TK', 'value' => 'Tokelau'],
    'TO' => ['id' => 'TO', 'value' => 'Tonga'],
    'TT' => ['id' => 'TT', 'value' => 'Trinidad and Tobago'],
    'TN' => ['id' => 'TN', 'value' => 'Tunisia'],
    'TR' => ['id' => 'TR', 'value' => 'Turkey'],
    'TM' => ['id' => 'TM', 'value' => 'Turkmenistan'],
    'TC' => ['id' => 'TC', 'value' => 'Turks and Caicos Islands (the)'],
    'TV' => ['id' => 'TV', 'value' => 'Tuvalu'],
    'UG' => ['id' => 'UG', 'value' => 'Uganda'],
    'UA' => ['id' => 'UA', 'value' => 'Ukraine'],
    'AE' => ['id' => 'AE', 'value' => 'United Arab Emirates (the)'],
    'GB' => ['id' => 'GB', 'value' => 'United Kingdom of Great Britain and Northern Ireland (the)'],
    'UM' => ['id' => 'UM', 'value' => 'United States Minor Outlying Islands (the)'],
    'US' => ['id' => 'US', 'value' => 'United States of America (the)'],
    'UY' => ['id' => 'UY', 'value' => 'Uruguay'],
    'UZ' => ['id' => 'UZ', 'value' => 'Uzbekistan'],
    'VU' => ['id' => 'VU', 'value' => 'Vanuatu'],
    'VE' => ['id' => 'VE', 'value' => 'Venezuela (Bolivarian Republic of)'],
    'VN' => ['id' => 'VN', 'value' => 'Viet Nam'],
    'VG' => ['id' => 'VG', 'value' => 'Virgin Islands (British)'],
    'VI' => ['id' => 'VI', 'value' => 'Virgin Islands (U.S.)'],
    'WF' => ['id' => 'WF', 'value' => 'Wallis and Futuna'],
    'EH' => ['id' => 'EH', 'value' => 'Western Sahara*'],
    'YE' => ['id' => 'YE', 'value' => 'Yemen'],
    'ZM' => ['id' => 'ZM', 'value' => 'Zambia'],
    'ZW' => ['id' => 'ZW', 'value' => 'Zimbabwe']
];
