<?php

//Catálogo N° 15:

return [
    '1000' => ['id' => '1000', 'value' => 'Monto en Letras'],
    '1002' => ['id' => '1002', 'value' => 'Leyenda "TRANSFERENCIA GRATUITA DE UN BIEN Y/O SERVICIO PRESTADO GRATUITAMENTE"'],
    '2000' => ['id' => '2000', 'value' => 'Leyenda "COMPROBANTE DE PERCEPCIÓN"'],
    '2001' => ['id' => '2001', 'value' => 'Leyenda "BIENES TRANSFERIDOS EN LA AMAZONÍA REGIÓN SELVAPARA SER CONSUMIDOS EN LA MISMA"'],
    '2002' => ['id' => '2002', 'value' => 'Leyenda "SERVICIOS PRESTADOS EN LA AMAZONÍA  REGIÓN SELVA PARA SER CONSUMIDOS EN LA MISMA"'],
    '2003' => ['id' => '2003', 'value' => 'Leyenda "CONTRATOS DE CONSTRUCCIÓN EJECUTADOS  EN LA AMAZONÍA REGIÓN SELVA"'],
    '2004' => ['id' => '2004', 'value' => 'Leyenda "Agencia de Viaje - Paquete turístico" '],
    '2005' => ['id' => '2005', 'value' => 'Leyenda "Venta realizada por emisor itinerante"'],
    '2006' => ['id' => '2006', 'value' => 'Leyenda: Operación sujeta a detracción'],
    '2007' => ['id' => '2007', 'value' => 'Leyenda: Operación sujeta a IVAP'],
    '3000' => ['id' => '3000', 'value' => 'Detracciones: CODIGO DE BB Y SS SUJETOS A DETRACCION'],
    '3001' => ['id' => '3001', 'value' => 'Detracciones: NUMERO DE CTA EN EL BN'],
    '3002' => ['id' => '3002', 'value' => 'Detracciones: Recursos Hidrobiológicos-Nombre y matrícula de la embarcación'],
    '3003' => ['id' => '3003', 'value' => 'Detracciones: Recursos Hidrobiológicos-Tipo y cantidad de especie vendida'],
    '3004' => ['id' => '3004', 'value' => 'Detracciones: Recursos Hidrobiológicos -Lugar de descarga'],
    '3005' => ['id' => '3005', 'value' => 'Detracciones: Recursos Hidrobiológicos -Fecha de descarga'],
    '3006' => ['id' => '3006', 'value' => 'Detracciones: Transporte Bienes vía terrestre – Numero Registro MTC'],
    '3007' => ['id' => '3007', 'value' => 'Detracciones: Transporte Bienes vía terrestre – configuración vehicular'],
    '3008' => ['id' => '3008', 'value' => 'Detracciones: Transporte Bienes vía terrestre – punto de origen'],
    '3009' => ['id' => '3009', 'value' => 'Detracciones: Transporte Bienes vía terrestre – punto destino'],
    '3010' => ['id' => '3010', 'value' => 'Detracciones: Transporte Bienes vía terrestre – valor referencial preliminar'],
    '4000' => ['id' => '4000', 'value' => 'Beneficio hospedajes: Código País de emisión del pasaporte'],
    '4001' => ['id' => '4001', 'value' => 'Beneficio hospedajes: Código País de residencia del sujeto no domiciliado'],
    '4002' => ['id' => '4002', 'value' => 'Beneficio Hospedajes: Fecha de ingreso al país '],
    '4003' => ['id' => '4003', 'value' => 'Beneficio Hospedajes: Fecha de ingreso al establecimiento'],
    '4004' => ['id' => '4004', 'value' => 'Beneficio Hospedajes: Fecha de salida del establecimiento'],
    '4005' => ['id' => '4005', 'value' => 'Beneficio Hospedajes: Número de días de permanencia'],
    '4006' => ['id' => '4006', 'value' => 'Beneficio Hospedajes: Fecha de consumo '],
    '4007' => ['id' => '4007', 'value' => 'Beneficio Hospedajes: Paquete turístico - Nombres y Apellidos del Huésped '],
    '4008' => ['id' => '4008', 'value' => 'Beneficio Hospedajes: Paquete turístico – Tipo documento identidad del huésped  '],
    '4009' => ['id' => '4009', 'value' => 'Beneficio Hospedajes: Paquete turístico – Numero de documento identidad de huésped '],
    '5000' => ['id' => '5000', 'value' => 'Proveedores Estado: Número de Expediente'],
    '5001' => ['id' => '5001', 'value' => 'Proveedores Estado : Código de unidad ejecutora'],
    '5002' => ['id' => '5002', 'value' => 'Proveedores Estado : Nro. de proceso de selección'],
    '5003' => ['id' => '5003', 'value' => 'Proveedores Estado : Nro. de contrato'],
    '6000' => ['id' => '6000', 'value' => 'Comercialización de Oro :  Código Unico Concesión Minera'],
    '6001' => ['id' => '6001', 'value' => 'Comercialización de Oro :  Nro. declaración compromiso'],
    '6002' => ['id' => '6002', 'value' => 'Comercialización de Oro :  Nro. Reg. Especial .Comerci. Oro'],
    '6003' => ['id' => '6003', 'value' => 'Comercialización de Oro :  Nro. Resolución que autoriza Planta de Beneficio'],
    '6004' => ['id' => '6004', 'value' => 'Comercialización de Oro : Ley Mineral (% concent. oro)']
];
